/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Sign_Up = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton_Sign_In = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        jLabel1.setText("Stylish TL Shop");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 260, 40);

        jLabel2.setFont(new java.awt.Font("Saysettha OT", 0, 18)); // NOI18N
        jLabel2.setText("ີຍິນດີຕ້ອນຮັບ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 60, 120, 50);

        jButton_Sign_Up.setBackground(new java.awt.Color(255, 153, 153));
        jButton_Sign_Up.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Sign_Up.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Sign_Up.setText("SIGN UP");
        jButton_Sign_Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Sign_UpMouseClicked(evt);
            }
        });
        jButton_Sign_Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sign_UpActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Sign_Up);
        jButton_Sign_Up.setBounds(110, 260, 100, 40);

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(370, 120, 310, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 80, 100, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 180, 80, 25);

        jPasswordField1.setBackground(new java.awt.Color(255, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(370, 220, 310, 30);

        jButton_Sign_In.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_Sign_In.setText("SIGN IN");
        jButton_Sign_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Sign_InMouseClicked(evt);
            }
        });
        jButton_Sign_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sign_InActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Sign_In);
        jButton_Sign_In.setBounds(460, 320, 100, 40);

        jLabel6.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jLabel6.setText("ລົງທະບຽນບ່ອນນີ້ສຳລັບລູກຄ້າໃໝ່");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 310, 160, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-02-27 160852.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(360, 390));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 320, 390);

        jLabel7.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ລົງທະບຽນສຳລັບສະມາຊິກ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 290, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton_Sign_UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Sign_UpMouseClicked
        Sign_Up su = new Sign_Up();
        su.setVisible(true);
        su.pack();
        su.setLocationRelativeTo(null);
        //rg.setDefaultCloseOperation(jButton_Sign_In.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jButton_Sign_UpMouseClicked

    private void jButton_Sign_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Sign_InMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_Sign_InMouseClicked

    private void jButton_Sign_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sign_InActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Sign_InActionPerformed

    private void jButton_Sign_UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sign_UpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Sign_UpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Sign_In;
    private javax.swing.JButton jButton_Sign_Up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
